[package]
name = "zara-demo"
version = "0.1.0"
authors = ["Vadim Gromov <zara-survival@imw.su>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="zara-demo"
path="src/main.rs"

[dependencies]
zara = { path = "../zara" }
